[MTLmicro]
extends = nrf52_base
board = promicro_nrf52840
build_flags = ${nrf52_base.build_flags}
  -I variants/mtlmicro
  -Wl,--wrap=loop
  -D MTLMICRO
  -D LORA_TX_POWER=22
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D PIN_BOARD_SCL=11	; P0.11
  -D PIN_BOARD_SDA=36	; P1.04 
  -D PIN_OLED_RESET=-1
  -D PIN_BUZZER=6	  	; P0.6
  -D PIN_VIBRATION=8	; P0.8
  -D ENV_INCLUDE_AHTX0=1
  -D ENV_INCLUDE_BME280=1
  -D ENV_INCLUDE_BMP280=1
  -D ENV_INCLUDE_INA3221=1
  -D ENV_INCLUDE_INA219=1
build_src_filter = ${nrf52_base.build_src_filter}
  +<helpers/sensors>
  +<helpers/ui/buzzer.cpp>
  +<helpers/ui/GenericVibration.cpp>
  +<../variants/mtlmicro>
lib_deps= ${nrf52_base.lib_deps}
	adafruit/Adafruit SSD1306 @ ^2.5.13
  adafruit/Adafruit SH110X @ ^2.1.14
  adafruit/Adafruit INA3221 Library @ ^1.0.1
  adafruit/Adafruit INA219 @ ^1.2.3
  adafruit/Adafruit AHTX0 @ ^2.0.5
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/Adafruit BMP280 Library@^2.6.8
  stevemarple/MicroNMEA @ ^2.0.6
  end2endzone/NonBlockingRTTTL@^1.3.0

[env:MTLmicro_sx1262_SH1106_companion_radio_usb]
extends = MTLmicro
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${MTLmicro.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D DISPLAY_CLASS=SH1106Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=1
  -D PIN_GPS_RX=20	 	; P0.20 
  -D PIN_GPS_TX=22 		; P0.22
  -D PIN_GPS_EN=24 		; P0.24
  -D GPS_EN_ACTIVE=LOW
; NOTE: DO NOT ENABLE -->  -D MESH_PACKET_LOGGING=1
; NOTE: DO NOT ENABLE -->  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0

[env:MTLmicro_sx1262_SH1106_companion_radio_ble]
extends = MTLmicro
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${MTLmicro.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
  -D DISPLAY_CLASS=SH1106Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=1
  -D PIN_GPS_RX=20	 	; P0.20 
  -D PIN_GPS_TX=22 		; P0.22
  -D PIN_GPS_EN=24 		; P0.24
;  -D MESH_PACKET_LOGGING=1
  -D MESH_DEBUG=1
  -D GPS_EN_ACTIVE=LOW
build_src_filter = ${MTLmicro.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0

[env:MTLmicro_sx1262_SH1106_repeater]
extends = MTLmicro
build_flags =
  ${MTLmicro.build_flags}
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D ADVERT_NAME='"MTL-2 UART Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SH1106Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=0
  -D WITH_RS232_BRIDGE=Serial2
  -D WITH_RS232_BRIDGE_RX=PIN_SERIAL2_RX
  -D WITH_RS232_BRIDGE_TX=PIN_SERIAL2_TX
  -UENV_INCLUDE_GPS
;  -D BRIDGE_DEBUG=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/bridges/RS232Bridge.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
 
[env:MTLmicro_sx1262_SSD1306_companion_radio_ble]
extends = MTLmicro
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${MTLmicro.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
  -D DISPLAY_CLASS=SSD1306Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=1
  -D PIN_GPS_RX=20	 	; P0.20 
  -D PIN_GPS_TX=22 		; P0.22
  -D PIN_GPS_EN=24 		; P0.24
;  -D MESH_PACKET_LOGGING=1
  -D MESH_DEBUG=1
  -D GPS_EN_ACTIVE=LOW
build_src_filter = ${MTLmicro.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0

[env:MTLmicro_sx1262_SSD1306_repeater]
extends = MTLmicro
build_flags =
  ${MTLmicro.build_flags}
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D ADVERT_NAME='"MTL-2 UART Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SSD1306Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=0
  -D WITH_RS232_BRIDGE=Serial2
  -D WITH_RS232_BRIDGE_RX=PIN_SERIAL2_RX
  -D WITH_RS232_BRIDGE_TX=PIN_SERIAL2_TX
  -UENV_INCLUDE_GPS
;  -D BRIDGE_DEBUG=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/bridges/RS232Bridge.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3

  ;--------E22-sx1262---433MHz--------------------------------------

[env:MTLmicro_sx1262_SH1106_433MHz_repeater]
extends = MTLmicro
build_flags =
  ${MTLmicro.build_flags}
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_FREQ=433.0
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D ADVERT_NAME='"MTL-2 UART Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SH1106Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=0
  -D WITH_RS232_BRIDGE=Serial2
  -D WITH_RS232_BRIDGE_RX=PIN_SERIAL2_RX
  -D WITH_RS232_BRIDGE_TX=PIN_SERIAL2_TX
  -UENV_INCLUDE_GPS
;  -D BRIDGE_DEBUG=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/bridges/RS232Bridge.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
 
[env:MTLmicro_sx1262_SSD1306_433MHz_repeater]
extends = MTLmicro
build_flags =
  ${MTLmicro.build_flags}
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_FREQ=433.0
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D ADVERT_NAME='"MTL-2 UART Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SSD1306Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=0
  -D WITH_RS232_BRIDGE=Serial2
  -D WITH_RS232_BRIDGE_RX=PIN_SERIAL2_RX
  -D WITH_RS232_BRIDGE_TX=PIN_SERIAL2_TX
  -UENV_INCLUDE_GPS
;  -D BRIDGE_DEBUG=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/bridges/RS232Bridge.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3

;-----------------e22p-SX1268---433MHz-----------------

[env:MTLmicro_sx1268_SH1106_companion_radio_usb]
extends = MTLmicro
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${MTLmicro.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D LORA_FREQ=433.0
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D DISPLAY_CLASS=SH1106Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=1
  -D PIN_GPS_RX=20	 	; P0.20 
  -D PIN_GPS_TX=22 		; P0.22
  -D PIN_GPS_EN=24 		; P0.24
  -D GPS_EN_ACTIVE=LOW
; NOTE: DO NOT ENABLE -->  -D MESH_PACKET_LOGGING=1
; NOTE: DO NOT ENABLE -->  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0

[env:MTLmicro_sx1268_SH1106_companion_radio_ble]
extends = MTLmicro
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${MTLmicro.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D LORA_FREQ=433.0
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
  -D DISPLAY_CLASS=SH1106Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=1
  -D PIN_GPS_RX=20	 	; P0.20 
  -D PIN_GPS_TX=22 		; P0.22
  -D PIN_GPS_EN=24 		; P0.24
  -D GPS_EN_ACTIVE=LOW
;  -D MESH_PACKET_LOGGING=1
  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0

[env:MTLmicro_sx1268_SH1106_repeater]
extends = MTLmicro
build_flags =
  ${MTLmicro.build_flags}
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D LORA_FREQ=433.0
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D ADVERT_NAME='"MTL-2 UART Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SH1106Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=0
  -D WITH_RS232_BRIDGE=Serial2
  -D WITH_RS232_BRIDGE_RX=PIN_SERIAL2_RX
  -D WITH_RS232_BRIDGE_TX=PIN_SERIAL2_TX
  -UENV_INCLUDE_GPS
;  -D BRIDGE_DEBUG=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
  +<helpers/ui/SH1106Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/bridges/RS232Bridge.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3

;----------e22p---sx1268--SSD1306---433MHz----

[env:MTLmicro_sx1268_SSD1306_companion_radio_usb]
extends = MTLmicro
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${MTLmicro.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D LORA_FREQ=433.0
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D DISPLAY_CLASS=SSD1306Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=1
  -D PIN_GPS_RX=20	 	; P0.20 
  -D PIN_GPS_TX=22 		; P0.22
  -D PIN_GPS_EN=24 		; P0.24
  -D GPS_EN_ACTIVE=LOW
; NOTE: DO NOT ENABLE -->  -D MESH_PACKET_LOGGING=1
; NOTE: DO NOT ENABLE -->  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0

[env:MTLmicro_sx1268_SSD1306_companion_radio_ble]
extends = MTLmicro
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${MTLmicro.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D LORA_FREQ=433.0
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
  -D DISPLAY_CLASS=SSD1306Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=1
  -D PIN_GPS_RX=20	 	; P0.20 
  -D PIN_GPS_TX=22 		; P0.22
  -D PIN_GPS_EN=24 		; P0.24
  -D GPS_EN_ACTIVE=LOW
;  -D MESH_PACKET_LOGGING=1
  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0

[env:MTLmicro_sx1268_SSD1306_repeater]
extends = MTLmicro
build_flags =
  ${MTLmicro.build_flags}
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D LORA_FREQ=433.0
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D ADVERT_NAME='"MTL-2 UART Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SSD1306Display
  -D UI_HAS_JOYSTICK=1
  -D ENV_INCLUDE_GPS=0
  -D WITH_RS232_BRIDGE=Serial2
  -D WITH_RS232_BRIDGE_RX=PIN_SERIAL2_RX
  -D WITH_RS232_BRIDGE_TX=PIN_SERIAL2_TX
  -UENV_INCLUDE_GPS
;  -D BRIDGE_DEBUG=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${MTLmicro.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/bridges/RS232Bridge.cpp>
lib_deps = ${MTLmicro.lib_deps}
  adafruit/RTClib @ ^2.1.3